language: python

python:
  - 2.7
  - 3.4 # TODO Should I update this to latest Python version?

# Command to install dependencies
install: pip install -r requirements.txt

# Command to run tests
script: python tests/test_nrrd.py

deploy:
  provider: pypi
  user: "addisonElliott"
  password:
    secure: "Your encrypted password"
  on:
    tags: true
  distributions: "sdist bdist_wheel" # TODO IS this what I want to do? Your distributions here